[workspace]
resolver = "3"
members = ["crates/backend", "crates/server", "crates/tauri-app"]

[patch.crates-io]
muda = { git = "https://github.com/Piebald-AI/muda", branch = "fix-top-level-submenu-padding-issue" }
